<?php
/**
 * Created by PhpStorm.
 * User: zhuguangwen
 * Date: 15/7/17
 * Time: 下午5:54
 */

class Config{

    //input file names
    const entity_file_name = "entity.txt";
    const api_file_name = "api.txt";

    //output file names
    const output_folder = "network/";
    const output_const_int_file_name = "ServerConfig.h";
    const output_const_api_string_file_name = "ApiConfig.h";

    //const string for generate code
    const file_prefix = "//this file is generated by program, you should not change this file";

}