//this file is automatically generated by program, you should not change this file

#import <Fundation.h>

static const NSInteger YES = 1;
static const NSInteger NO = 0;

static NSString const *kUserApiGetUserInfo = @"user_api/get_user_info";
static NSString const *kUserApiIsSinger = @"user_api/is_singer";

static NSString const *kGameApiGameStart = @"game_api/game_start";
