//this file is generated by program, you should not change this file
//Created automatically on 15-07-18 01:21:22

#import <Fundation.h>
//api
static NSString const *kUserApiGetUserInfo = @"user_api/get_user_info";
static NSString const *kUserApiIsSinger = @"user_api/is_singer";

static NSString const *kGameApiGameStart = @"game_api/game_start";
