//this file is generated by program, you should not change this file
//Created automatically on 15-07-19 23:41:14

#import <Fundation.h>
#import "HttpEntity.h.h"

@implementation User
@end

@implementation Game
@end
