//this file is generated by program, you should not change this file
//Created automatically on 15-07-18 01:21:22

#import <Fundation.h>
//const int
static const NSInteger YES = 1;
static const NSInteger NO = 0;
