//this file is generated by program, you should not change this file
//Created automatically on 15-07-18 01:21:22

#import <Fundation.h>
@interface User
@property (nonatomic, assign) NSInteger user_id;
@property (nonatomic, strong) NSString *name;
@property (nonatomic, assign) NSInteger is_male;
@property (nonatomic, assign) NSInteger create_time;
@end
